# Generated by Django 2.2.1 on 2019-05-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190519_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_validated',
            field=models.BooleanField(default=True),
        ),
    ]
